[package]
name = "frusco"
version = "0.1.0"
authors = ["bobgates <>"]

[dependencies]
three = "*"
nalgebra = "0.12.0"
rust-3d="0.19.0"
cgmath="0.14"

#Conrod and supporting crates
conrod = {version = "0.54", features = ["glium", "winit"] }
find_folder = "0.3.0"
rand = "0.3.13"
image = "0.13.0"

